kind: pipeline
name: Format Python code, etc.

trigger:
  branch:
  - master

steps:
- name: Checkout the master branch
  image: python:bullseye
  commands:
    - git checkout master

- name: Install additional software
  image: python:bullseye
  commands:
    - apt update
    - echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' |  tee /etc/apt/sources.list.d/shells:fish:release:3.list
    - curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor |  tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
    - apt update
    - apt install -y fish
    - fish --version

- name: Print the git status
  image: python
  commands:
    - git status
    - echo "Current commit is $(git log --pretty=format:'%h' -n 1)"

- name: Format code if required
  image: python
  commands:
    - python -m pip install black
    - black .
    - git diff --quiet && git diff --staged --quiet || git commit -am '[DRONE] [CI SKIP] Formatted code'
    - git push --set-upstream origin master

---
kind: pipeline
name: Update main bastion tools when pushing to release

trigger:
  branch:
  - dev

steps:
- name: Checkout dev branch instead of default branch
  image: python
  commands:
    - git checkout dev

- name: Print the git status
  image: python
  commands:
    - git status
    - echo "Current commit is $(git log --pretty=format:'%h' -n 1)"

- name: Format code if required
  image: python
  commands:
    - python -m pip install black
    - black .
    - git diff --quiet && git diff --staged --quiet || git commit -am '[DRONE] [CI SKIP] Formatted code'
    - git push --set-upstream origin master
